.\" Hey, EMACS: -*- nroff -*-
.\" for manpage-specific macros, see man(7)
.TH "PAUSEME" "1" "August 27, 2002" "Edelhard Becker" "Utility"
.SH "NAME"
pauseme \- a helper script for vifm
.SH "SYNOPSIS"
only called automagically from within vifm
.SH "DESCRIPTION"
A helper script for vifm, not for standalone use.
.SH "SEE ALSO"
\fBvifm\fR (1),
.SH "AUTHOR"
This manual page was written by Edelhard Becker <becker@edelhard.de>,
for the Debian GNU/Linux system (but may be used by others).
