#! /bin/sh
# prerm script for vifm
#

set -e

case "$1" in
    remove|upgrade|deconfigure)
    rm -f /etc/vim/plugin/vifm.vim /etc/vim/doc/vifm.txt
        ;;
    failed-upgrade)
        ;;
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

